kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crbind-myuser2-read
subjects:
- kind: ServiceAccount
  name: myuser2
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: crole-read-cluster-pod
  apiGroup: "rbac.authorization.k8s.io"
