apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-job
spec:
  template:
    metadata:
      labels:
        app: myapp-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: myapp
        image: busybox
        command: ["sleep", "60"]
