apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-job-always-test
spec:
  template:
    metadata:
      labels:
        app: myapp-job
    spec:
      restartPolicy: Always
      containers:
      - name: myapp
        image: busybox
        command: ["sleep", "30"]
