apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: myapp-cj
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
           labels:
             app: myapp-cj
        spec:
          restartPolicy: OnFailure
          containers:
          - name: myapp
            image: busybox
            command: ["sleep", "60"]
